apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 2
  name: poinfo-subchart
  namespace: argocd
spec:
  destination:
    namespace: helm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/dharmendrakariya/argocd-demo
    targetRevision: helm
  syncPolicy:
    automated: {}
status:
  health:
    status: Healthy
  reconciledAt: "2021-09-24T08:37:30Z"
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: helm
        server: https://kubernetes.default.svc
      source:
        path: ./
        repoURL: https://github.com/dharmendrakariya/argocd-demo
        targetRevision: helm
    revision: 29524249d3f341d5840e285f270984c8b229a796
    status: Synced
