# Default values for podinfo.
demo7:
  replicaCount: 1

  image:
    repository: dharmendrakariya/circle-app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1.10"
    
  ingress:
    enabled: true
    className: ""
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: circle.myownsky.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
